doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            rating: App\Infrastructure\Type\RatingType
            comment: App\Infrastructure\Type\CommentType
            translatable: App\Infrastructure\Type\TranslatableType
    
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Domain\Category:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Category'
                prefix: 'App\Domain\Product'
                alias: App\Domain\Category
            App\Domain\Product:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Product'
                prefix: 'App\Domain\Product'
                alias: App\Domain\Product
            App\Domain\Review:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Review'
                prefix: 'App\Domain\Review'
                alias: App\Domain\Review
            App\Domain\User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/User'
                prefix: 'App\Domain\User'
                alias: App\Domain\User