doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            rating: App\Infrastructure\Type\RatingType
            comment: App\Infrastructure\Type\CommentType
    
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        # server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Domain\Product:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Product/Entity'
                prefix: 'App\Domain\Product\Entity'
                alias: App\Domain\Product
            App\Domain\Review:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Review/Entity'
                prefix: 'App\Domain\Review\Entity'
                alias: App\Domain\Review
            App\Domain\User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/User/Entity'
                prefix: 'App\Domain\User\Entity'
                alias: App\Domain\User