security:
    encoders:
        App\User\Entity\User:
            algorithm: auto
            cost: 12
    providers:
        app_user_provider:
            entity:
                class: App\User\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               jwt_login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        main:
            anonymous: true
            stateless: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Infrastructure\Security\ImportAuthenticator
                    - lexik_jwt_authentication.jwt_token_authenticator
                entry_point: lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/import, roles: ROLE_IMPORT }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/frontend/review, roles: [IS_AUTHENTICATED_FULLY] }