version: "3.1"
services:
    webserver:
      image: nginx:alpine
      container_name: terry-api-show-webserver
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8040:80"
        - "8041:81"
    dev:
      build: docker/dev
      container_name: terry-api-show-dev
      working_dir: /app
      env_file:
        - ./docker/dev/.env
      volumes:
        - ./vendor:/app/vendor:cached
        - .:/app:delegated  
    prod:
      build: docker/prod  
      container_name: terry-api-show-prod
      working_dir: /app
      volumes:
        - .:/app:cached
    db:
      image: postgres:11
      container_name: terry-api-show-db
      volumes:
        - ./docker/db/pg-init-scripts:/docker-entrypoint-initdb.d
      restart: always
      ports:
        - "8042:5432"
      environment:
        POSTGRES_MULTIPLE_DATABASES: app,app_test
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass